steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--tag=gcr.io/whitelist-test-291918/my-app']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['g++', '-o', 'my-app', 'main.cpp']

images:
- 'gcr.io/whitelist-test-291918/my-app'
